# ============================================================
# Mini-SIEM - zentraler rsyslog Server
# ============================================================


# ------------------------------------------------------------
# UDP Syslog Empfang aktivieren
# ------------------------------------------------------------

# Modul für UDP-Empfang laden.
module(load="imudp")

# UDP Port 514 für eingehende Syslog-Nachrichten öffnen.
input(
    type="imudp"
    port="514"
)


# ------------------------------------------------------------
# Dynamischen Speicherpfad definieren
# ------------------------------------------------------------

# Logs werden nach folgendem Schema gespeichert:
#
# /var/log/remote/<HOSTNAME>/<PROGRAMM>.log
#
# Beispiel:
#
# /var/log/remote/log-client/sshd.log
#
template(
    name="RemoteLogs"
    type="string"
    string="/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log"
)


# ------------------------------------------------------------
# Remote Logs speichern
# ------------------------------------------------------------

# Lokale Nachrichten von 127.0.0.1 sollen hier nicht erneut
# als Remote-Logs gespeichert werden.
if $fromhost-ip != '127.0.0.1' then {

    action(
        # Logs in Dateien schreiben.
        type="omfile"

        # Den oben definierten dynamischen Dateipfad verwenden.
        dynaFile="RemoteLogs"

        # Fehlende Verzeichnisse automatisch erzeugen.
        createDirs="on"

        # ----------------------------------------------------
        # Rechte für automatisch erzeugte Verzeichnisse
        # ----------------------------------------------------

        # Besitzer neuer Verzeichnisse.
        dirOwner="root"

        # Gruppe neuer Verzeichnisse.
        dirGroup="mini-siem"

        # Verzeichnisrechte:
        #
        # root       = rwx
        # mini-siem  = r-x
        # andere     = ---
        dirCreateMode="0750"


        # ----------------------------------------------------
        # Rechte für automatisch erzeugte Logdateien
        # ----------------------------------------------------

        # Besitzer der Logdateien.
        fileOwner="root"

        # Gruppe der Logdateien.
        fileGroup="mini-siem"

        # Dateirechte:
        #
        # root       = rw-
        # mini-siem  = r--
        # andere     = ---
        fileCreateMode="0640"
    )

    # Nachricht wurde verarbeitet.
    # Keine weiteren rsyslog-Regeln anwenden.
    stop
}